//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebbanBALO.Areas.Admin.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string TKad { get; set; }
        public string MKad { get; set; }
    }
}
