//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebbanBALO.Areas.Admin.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTdonhang
    {
        public int Madon { get; set; }
        public int Masp { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual Donhang Donhang { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
