//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebbanBALO.Areas.Admin.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhmuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Danhmuc()
        {
            this.Danhmuc1 = new HashSet<Danhmuc>();
            this.Sanphams = new HashSet<Sanpham>();
        }
    
        public int Madm { get; set; }
        public string Tendm { get; set; }
        public string Tenvt { get; set; }
        public Nullable<int> Macha { get; set; }
        public Nullable<int> Thutusx { get; set; }
        public string Thutuht { get; set; }
        public Nullable<bool> Trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danhmuc> Danhmuc1 { get; set; }
        public virtual Danhmuc Danhmuc2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanpham> Sanphams { get; set; }
    }
}
